/**
 * Manual "Create PR" per project/branch (DESIGN.md decision 6): bundle all
 * done tasks' commits on a branch into ONE PR — push the branch, `gh pr
 * create` (or push into the already-open PR), body generated from the done
 * tasks (titles, summaries, non-blocking review findings).
 */

import type { BranchPR, ReviewVerdict, Task, TaskEvent } from "@/lib/types";
import { upsertBranchPr } from "@/server/db/branchPrs";
import { listTaskEvents, listTasksByProject } from "@/server/db/tasks";
import { prCreate, prEditBody, prList, push } from "@/server/git";
import { publish } from "@/server/bus";
import { notify } from "@/server/notify";
import { InvalidTransitionError, transition } from "./stateMachine";
import { requireProject } from "./common";

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null;
}

/** Extract the verdict from a review_* event payload, if present. */
function verdictFromEvent(event: TaskEvent): ReviewVerdict | undefined {
  if (!isRecord(event.payload)) return undefined;
  const verdict = event.payload.verdict;
  return isRecord(verdict) && "findings" in verdict ? (verdict as unknown as ReviewVerdict) : undefined;
}

/** Last dev_completed summary (the implementer's closing message). */
function summaryFromEvents(events: TaskEvent[]): string | undefined {
  for (let i = events.length - 1; i >= 0; i--) {
    const e = events[i];
    if (!e) continue;
    if (e.type === "dev_completed" && isRecord(e.payload) && typeof e.payload.summary === "string") {
      const s = e.payload.summary.trim();
      if (s.length > 0) return s;
    }
  }
  return undefined;
}

function hasPrCreatedEvent(events: TaskEvent[]): boolean {
  return events.some((e) => e.type === "pr_created");
}

interface TaskBundle {
  task: Task;
  summary?: string;
  nonBlockingFindings: ReviewVerdict["findings"];
  alreadyInPr: boolean;
}

/**
 * The branch a task's commits actually live on (the PR head). For worktree
 * tasks that is the dedicated `friday/<name>` worktree branch; for branch /
 * new-branch mode it's `task.branch` (new-branch mode retargets task.branch to
 * the friday/<slug> branch during workspace prep, so it's already the head).
 */
export function prHeadBranch(task: Task): string {
  return task.workspaceMode === "worktree" && task.worktree ? task.worktree.branch : task.branch;
}

/** Done, local tasks whose PR head branch matches — what a PR bundles. */
export function listDonePrTasks(projectId: string, branch: string): Task[] {
  return listTasksByProject(projectId).filter(
    (t) => t.column === "done" && t.execution === "local" && prHeadBranch(t) === branch,
  );
}

function collectBundle(projectId: string, branch: string): TaskBundle[] {
  const doneTasks = listDonePrTasks(projectId, branch);
  return doneTasks.map((task) => {
    const events = listTaskEvents(task.id);
    const findings: ReviewVerdict["findings"] = [];
    for (const e of events) {
      if (e.type !== "review_approved") continue;
      const verdict = verdictFromEvent(e);
      if (verdict) {
        findings.push(...verdict.findings.filter((f) => f.severity !== "blocker"));
      }
    }
    return {
      task,
      summary: summaryFromEvents(events),
      nonBlockingFindings: findings,
      alreadyInPr: hasPrCreatedEvent(events),
    };
  });
}

function buildPrBody(bundles: TaskBundle[], branch: string): string {
  const lines: string[] = [
    `Bundled changes from ${bundles.length} friday-kanban task(s) on \`${branch}\`.`,
    "",
  ];
  for (const { task, summary, nonBlockingFindings } of bundles) {
    lines.push(`## ${task.title}`, "");
    if (summary) {
      lines.push(summary, "");
    } else {
      lines.push(task.prompt.split("\n")[0] ?? task.prompt, "");
    }
    if (task.commitShas.length > 0) {
      lines.push(`Commits: ${task.commitShas.map((s) => `\`${s.slice(0, 8)}\``).join(", ")}`, "");
    }
    if (nonBlockingFindings.length > 0) {
      lines.push("**Review notes (non-blocking):**", "");
      for (const f of nonBlockingFindings) {
        lines.push(
          `- [${f.severity}] \`${f.file}${f.line !== undefined ? `:${f.line}` : ""}\` — ${f.comment}`,
        );
      }
      lines.push("");
    }
  }
  lines.push("---", "", "_Generated by friday-kanban._");
  return lines.join("\n");
}

/**
 * Create (or update) the bundled PR for (project, branch). Throws
 * InvalidTransitionError when the branch has no done tasks to bundle.
 */
export async function createPrForProjectBranch(
  projectId: string,
  branch: string,
): Promise<BranchPR> {
  const project = requireProject(projectId);
  const bundles = collectBundle(projectId, branch);

  if (bundles.length === 0) {
    throw new InvalidTransitionError(`No done tasks on ${project.name}:${branch} to bundle into a PR`);
  }
  const newBundles = bundles.filter((b) => !b.alreadyInPr);

  // 1. Push the branch (new commits flow into any open PR automatically).
  await push(project.path, branch);

  // 2. Reuse the open PR for this head if one exists, else create.
  const openPrs = await prList(project.path, { head: branch, state: "open" });
  const existing = openPrs[0];

  let prUrl: string;
  const body = buildPrBody(bundles, branch);
  if (existing) {
    prUrl = existing.url;
    // Refresh the body so newly bundled tasks are described too.
    await prEditBody(project.path, existing.number, body).catch((err: unknown) => {
      console.warn(`[prCreator] gh pr edit failed (non-fatal): ${String(err)}`);
    });
  } else {
    const first = bundles[0];
    const title =
      bundles.length === 1 && first
        ? first.task.title
        : `friday: ${branch} (${bundles.length} tasks)`;
    prUrl = await prCreate(project.path, {
      title,
      body,
      head: branch,
      base: project.baseBranch !== branch ? project.baseBranch : undefined,
    });
  }

  // 3. Record pr_created on each newly bundled task.
  for (const { task } of newBundles) {
    transition(task.id, "pr_created", { payload: { prUrl, branch } });
  }

  // 4. Upsert + publish the BranchPR record.
  const branchPr = upsertBranchPr(projectId, branch, prUrl);
  publish({ type: "branch_pr_updated", branchPr });
  notify("friday-kanban: PR ready", `${project.name}:${branch} → ${prUrl}`);
  return branchPr;
}
