/**
 * Manual "Create PR" per project/branch (DESIGN.md decision 6): bundle all
 * done tasks' commits on a branch into ONE PR — push the branch, `gh pr
 * create` (or push into the already-open PR), body generated from the done
 * tasks (titles, summaries, non-blocking review findings).
 */

import type { BranchPR, ReviewVerdict, Task, TaskEvent } from "@/lib/types";
import { upsertBranchPr } from "@/server/db/branchPrs";
import { listTaskEvents, listTasksByProject } from "@/server/db/tasks";
import { branchExists, hasRemote, prCreate, prEditBody, prList, push, revList } from "@/server/git";
import { publish } from "@/server/bus";
import { notify } from "@/server/notify";
import { InvalidTransitionError, transition } from "./stateMachine";
import { requireProject } from "./common";
import { isMultiRepo, projectRepos, taskBranchForRepo } from "./repos";

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null;
}

/** Extract the verdict from a review_* event payload, if present. */
function verdictFromEvent(event: TaskEvent): ReviewVerdict | undefined {
  if (!isRecord(event.payload)) return undefined;
  const verdict = event.payload.verdict;
  return isRecord(verdict) && "findings" in verdict ? (verdict as unknown as ReviewVerdict) : undefined;
}

/** Last dev_completed summary (the implementer's closing message). */
function summaryFromEvents(events: TaskEvent[]): string | undefined {
  for (let i = events.length - 1; i >= 0; i--) {
    const e = events[i];
    if (!e) continue;
    if (e.type === "dev_completed" && isRecord(e.payload) && typeof e.payload.summary === "string") {
      const s = e.payload.summary.trim();
      if (s.length > 0) return s;
    }
  }
  return undefined;
}

function hasPrCreatedEvent(events: TaskEvent[]): boolean {
  return events.some((e) => e.type === "pr_created");
}

interface TaskBundle {
  task: Task;
  summary?: string;
  nonBlockingFindings: ReviewVerdict["findings"];
  alreadyInPr: boolean;
}

/**
 * The branch a task's commits actually live on (the PR head). For worktree
 * tasks that is the dedicated `friday/<name>` worktree branch; for branch /
 * new-branch mode it's `task.branch` (new-branch mode retargets task.branch to
 * the friday/<slug> branch during workspace prep, so it's already the head).
 */
export function prHeadBranch(task: Task): string {
  return task.workspaceMode === "worktree" && task.worktree ? task.worktree.branch : task.branch;
}

/** Done, local tasks whose PR head branch matches — what a PR bundles. */
export function listDonePrTasks(projectId: string, branch: string): Task[] {
  return listTasksByProject(projectId).filter(
    (t) => t.column === "done" && t.execution === "local" && prHeadBranch(t) === branch,
  );
}

function collectBundle(projectId: string, branch: string): TaskBundle[] {
  const doneTasks = listDonePrTasks(projectId, branch);
  return doneTasks.map((task) => {
    const events = listTaskEvents(task.id);
    const findings: ReviewVerdict["findings"] = [];
    for (const e of events) {
      if (e.type !== "review_approved") continue;
      const verdict = verdictFromEvent(e);
      if (verdict) {
        findings.push(...verdict.findings.filter((f) => f.severity !== "blocker"));
      }
    }
    return {
      task,
      summary: summaryFromEvents(events),
      nonBlockingFindings: findings,
      alreadyInPr: hasPrCreatedEvent(events),
    };
  });
}

function buildPrBody(bundles: TaskBundle[], branch: string, repoName?: string): string {
  const scope = repoName ? `${repoName} · \`${branch}\`` : `\`${branch}\``;
  const lines: string[] = [
    `Bundled changes from ${bundles.length} friday-kanban task(s) on ${scope}.`,
    "",
  ];
  for (const { task, summary, nonBlockingFindings } of bundles) {
    lines.push(`## ${task.title}`, "");
    if (summary) {
      lines.push(summary, "");
    } else {
      lines.push(task.prompt.split("\n")[0] ?? task.prompt, "");
    }
    if (task.commitShas.length > 0) {
      lines.push(`Commits: ${task.commitShas.map((s) => `\`${s.slice(0, 8)}\``).join(", ")}`, "");
    }
    if (nonBlockingFindings.length > 0) {
      lines.push("**Review notes (non-blocking):**", "");
      for (const f of nonBlockingFindings) {
        lines.push(
          `- [${f.severity}] \`${f.file}${f.line !== undefined ? `:${f.line}` : ""}\` — ${f.comment}`,
        );
      }
      lines.push("");
    }
  }
  lines.push("---", "", "_Generated by friday-kanban._");
  return lines.join("\n");
}

/**
 * Push `branch` and create/refresh ONE PR in a single repo, then upsert +
 * publish its BranchPR record. `repoName` is passed only for multi-repo
 * projects (it scopes the PR record/title); single-repo callers omit it.
 */
async function createPrForRepo(
  repoPath: string,
  projectId: string,
  branch: string,
  baseBranch: string,
  bundles: TaskBundle[],
  repoName?: string,
): Promise<BranchPR> {
  // Push the branch (new commits flow into any open PR automatically).
  await push(repoPath, branch);

  // Reuse the open PR for this head if one exists, else create.
  const openPrs = await prList(repoPath, { head: branch, state: "open" });
  const existing = openPrs[0];

  let prUrl: string;
  const body = buildPrBody(bundles, branch, repoName);
  if (existing) {
    prUrl = existing.url;
    // Refresh the body so newly bundled tasks are described too.
    await prEditBody(repoPath, existing.number, body).catch((err: unknown) => {
      console.warn(`[prCreator] gh pr edit failed (non-fatal): ${String(err)}`);
    });
  } else {
    const first = bundles[0];
    const single = bundles.length === 1 && first;
    const title = single
      ? repoName
        ? `${first.task.title} (${repoName})`
        : first.task.title
      : `friday: ${repoName ? `${repoName} · ` : ""}${branch} (${bundles.length} tasks)`;
    prUrl = await prCreate(repoPath, {
      title,
      body,
      head: branch,
      base: baseBranch !== branch ? baseBranch : undefined,
    });
  }

  const branchPr = upsertBranchPr(projectId, branch, prUrl, repoName ? repoPath : "", repoName ?? "");
  publish({ type: "branch_pr_updated", branchPr });
  return branchPr;
}

/**
 * Create (or update) the bundled PR(s) for (project, branch). Single-repo
 * projects produce one PR; multi-repo projects produce one PR per sub-repo
 * that has commits on the branch. Throws InvalidTransitionError when the
 * branch has no done tasks to bundle (or no sub-repo changed).
 */
export async function createPrForProjectBranch(
  projectId: string,
  branch: string,
): Promise<BranchPR[]> {
  const project = requireProject(projectId);
  const bundles = collectBundle(projectId, branch);

  if (bundles.length === 0) {
    throw new InvalidTransitionError(`No done tasks on ${project.name}:${branch} to bundle into a PR`);
  }
  const newBundles = bundles.filter((b) => !b.alreadyInPr);

  // Single-repo: one PR against the project root (unchanged behavior).
  if (!isMultiRepo(project)) {
    const branchPr = await createPrForRepo(
      project.path,
      projectId,
      branch,
      project.baseBranch,
      bundles,
    );
    for (const { task } of newBundles) {
      transition(task.id, "pr_created", { payload: { prUrl: branchPr.prUrl, branch } });
    }
    notify("friday-kanban: PR ready", `${project.name}:${branch} → ${branchPr.prUrl}`);
    return [branchPr];
  }

  // Multi-repo: each task may target a different branch per repo. For every
  // repo, bundle the done tasks by the branch they target THERE, and open one
  // PR per (repo, branch) that actually has commits ahead of that repo's base.
  const created: BranchPR[] = [];
  const skipped: string[] = [];
  for (const repo of projectRepos(project)) {
    const byBranch = new Map<string, TaskBundle[]>();
    for (const b of bundles) {
      const rb = taskBranchForRepo(b.task, repo.path);
      const group = byBranch.get(rb) ?? [];
      group.push(b);
      byBranch.set(rb, group);
    }
    for (const [rb, group] of byBranch) {
      try {
        // Can't open a PR from a branch onto itself.
        if (rb === repo.baseBranch) continue;
        if (!(await branchExists(repo.path, rb))) continue;
        const ahead = await revList(repo.path, repo.baseBranch, rb).catch(() => [] as string[]);
        if (ahead.length === 0) continue; // nothing changed on this branch in this repo
        if (!(await hasRemote(repo.path))) {
          skipped.push(`${repo.name}#${rb}: no git remote`);
          continue;
        }
        created.push(
          await createPrForRepo(repo.path, projectId, rb, repo.baseBranch, group, repo.name),
        );
      } catch (err) {
        skipped.push(`${repo.name}#${rb}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }
  }

  if (created.length === 0) {
    throw new InvalidTransitionError(
      `No sub-repo of ${project.name} had changes on ${branch} to open a PR` +
        (skipped.length ? ` (${skipped.join("; ")})` : ""),
    );
  }

  for (const { task } of newBundles) {
    transition(task.id, "pr_created", {
      payload: { prUrls: created.map((p) => p.prUrl), branch },
    });
  }
  const summary = created.map((p) => `${p.repoName} → ${p.prUrl}`).join("  ·  ");
  const suffix = skipped.length ? ` (skipped ${skipped.length})` : "";
  notify("friday-kanban: PRs ready", `${project.name}:${branch} — ${summary}${suffix}`);
  return created;
}
